disabled_rules:
  - todo
  - line_length
  - identifier_name
  - inclusive_language
  - sorted_imports
excluded:
  - .build
  - DerivedData
  - KeyHandoverLog.xcodeproj
opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - sorted_imports
reporter: xcode
